window.EXAM_DATA = {
  nouns: [
    {es:"el matrimonio", zh:"婚姻", clue:"Román y Clotilde forman un buen ___.", answer:"matrimonio", note:"老师点名；第一册第16课", priority:3},
    {es:"el/la testigo", zh:"证人", clue:"Me llevaron de ___ a la comisaría.", answer:"testigo", note:"老师点名；第二册第3课", priority:3},
    {es:"la vida", zh:"生活", clue:"En la universidad tenemos una intensa ___ cultural.", answer:"vida", note:"老师点名；按名词填空判断为高概率答案", priority:3, uncertain:true},
    {es:"la cabeza", zh:"头", clue:"Tuvo un fuerte dolor de ___.", answer:"cabeza", note:"老师点名；第二册第5课", priority:3},
    {es:"el lugar", zh:"地方", clue:"Decidieron buscar un ___ donde aparcar el coche.", answer:"lugar", note:"老师点名；第二册第3课", priority:3},
    {es:"la comisaría", zh:"警察局", clue:"Llevar a alguien a la comisaría.", answer:"comisaría", priority:2},
    {es:"el coche", zh:"汽车", clue:"Aparcar el coche.", answer:"coche", priority:2},
    {es:"el metro", zh:"地铁", clue:"Tomar el metro.", answer:"metro", priority:2},
    {es:"el atasco", zh:"交通堵塞", clue:"Se produjo un terrible atasco.", answer:"atasco", priority:2},
    {es:"el accidente", zh:"事故", clue:"Un terrible accidente de tráfico.", answer:"accidente", priority:2},
    {es:"el tráfico", zh:"交通", clue:"El accidente paralizó el tráfico.", answer:"tráfico", priority:2},
    {es:"la ambulancia", zh:"救护车", clue:"Las ambulancias tardaron en llegar.", answer:"ambulancia", priority:1},
    {es:"el muerto / la muerta", zh:"死者", clue:"Hubo por lo menos cinco muertos.", answer:"muerto", priority:1},
    {es:"el herido / la herida", zh:"伤者", clue:"Hubo muchos heridos.", answer:"herido", priority:1},
    {es:"la pareja", zh:"夫妻；一对", clue:"La pareja trabaja en distintos centros.", answer:"pareja", priority:2},
    {es:"los quehaceres domésticos", zh:"家务", clue:"Encargarse de los quehaceres domésticos.", answer:"quehaceres domésticos", priority:2},
    {es:"el cansancio", zh:"疲劳", clue:"Se olvida del cansancio.", answer:"cansancio", priority:2},
    {es:"la satisfacción", zh:"满足", clue:"Sonríe con alegría y satisfacción.", answer:"satisfacción", priority:2},
    {es:"la cocina", zh:"厨房", clue:"En la cocina todo está a punto.", answer:"cocina", priority:1},
    {es:"las verduras", zh:"蔬菜", clue:"Las verduras bien lavadas.", answer:"verduras", priority:1},
    {es:"la carne", zh:"肉", clue:"La carne aliñada.", answer:"carne", priority:1},
    {es:"los utensilios", zh:"用具", clue:"Los cacharros y utensilios necesarios.", answer:"utensilios", priority:1},
    {es:"la conferencia", zh:"讲座", clue:"Asistir a una conferencia.", answer:"conferencia", priority:2},
    {es:"la literatura", zh:"文学", clue:"Literatura española y latinoamericana.", answer:"literatura", priority:1},
    {es:"los apuntes", zh:"笔记", clue:"Tomar apuntes.", answer:"apuntes", priority:1},
    {es:"el cuaderno", zh:"笔记本", clue:"Un cuaderno lleno.", answer:"cuaderno", priority:1},
    {es:"la disciplina", zh:"纪律", clue:"La vida de un estudiante necesita disciplina.", answer:"disciplina", priority:1},
    {es:"el colegio mayor", zh:"大学生宿舍；学院宿舍", clue:"Alojarse en un colegio mayor.", answer:"colegio mayor", priority:1},
    {es:"la beca", zh:"奖学金", clue:"Me dieron una beca.", answer:"beca", priority:1},
    {es:"el alojamiento", zh:"住宿", clue:"Encontrar alojamiento.", answer:"alojamiento", priority:1},
    {es:"el horario", zh:"时间表", clue:"Horarios rígidos y rigurosos.", answer:"horario", priority:1},
    {es:"el alquiler", zh:"房租", clue:"El alquiler se reparte entre todos.", answer:"alquiler", priority:1}
  ],
  articles: [
    {prompt:"___ profesora Verónica Hernández", answer:"la", tip:"profesora 是阴性名词，且指特定的那位老师。"},
    {prompt:"Recién llegada ___ Beijing", answer:"a", tip:"北京前通常不加冠词：a Beijing。"},
    {prompt:"___ Facultad de Español", answer:"la", tip:"Facultad 是阴性名词。"},
    {prompt:"___ misión muy grata", answer:"una", tip:"misión 是阴性名词。"},
    {prompt:"dar ___ bienvenida", answer:"la", tip:"固定搭配：dar la bienvenida。"},
    {prompt:"___ español como segunda lengua", answer:"el", tip:"语言名称在这里带定冠词。"},
    {prompt:"salir ___ la calle", answer:"a", tip:"固定搭配：salir a la calle。"},
    {prompt:"trabajar en ___ hospital público", answer:"un", tip:"hospital 是阳性名词。"},
    {prompt:"administrar ___ farmacia", answer:"una", tip:"farmacia 是阴性名词。"},
    {prompt:"encender ___ fuego", answer:"el", tip:"固定语境中的火：el fuego。"}
  ],
  verbs: [
    {inf:"estar", zh:"在；处于", forms:["estuve","estuviste","estuvo","estuvimos","estuvisteis","estuvieron"], example:"El sábado pasado estuve ausente de casa todo el día.", priority:3},
    {inf:"tener", zh:"有；不得不", forms:["tuve","tuviste","tuvo","tuvimos","tuvisteis","tuvieron"], example:"Tuvimos que esperar.", priority:3},
    {inf:"poder", zh:"能够", forms:["pude","pudiste","pudo","pudimos","pudisteis","pudieron"], example:"No pude conseguir un taxi.", priority:3},
    {inf:"ir / ser", zh:"去 / 是", forms:["fui","fuiste","fue","fuimos","fuisteis","fueron"], example:"Fue preciso bajar.", priority:3},
    {inf:"decir", zh:"说", forms:["dije","dijiste","dijo","dijimos","dijisteis","dijeron"], example:"Dijo: «Hasta la vista». ", priority:2},
    {inf:"pedir", zh:"点；请求", forms:["pedí","pediste","pidió","pedimos","pedisteis","pidieron"], example:"Pidió un café.", priority:2},
    {inf:"venir", zh:"来", forms:["vine","viniste","vino","vinimos","vinisteis","vinieron"], example:"¿Por qué no viniste?", priority:2},
    {inf:"llegar", zh:"到达", forms:["llegué","llegaste","llegó","llegamos","llegasteis","llegaron"], example:"Llegamos tarde al aeropuerto.", priority:2},
    {inf:"empezar", zh:"开始", forms:["empecé","empezaste","empezó","empezamos","empezasteis","empezaron"], example:"El tráfico empezó a atascarse.", priority:2},
    {inf:"producirse", zh:"发生", forms:["me produje","te produjiste","se produjo","nos produjimos","os produjisteis","se produjeron"], example:"Se produjo un terrible atasco.", priority:1},
    {inf:"perder", zh:"错过；失去", forms:["perdí","perdiste","perdió","perdimos","perdisteis","perdieron"], example:"Perdimos el avión.", priority:2},
    {inf:"encontrar", zh:"找到", forms:["encontré","encontraste","encontró","encontramos","encontrasteis","encontraron"], example:"No encontramos a nuestros amigos.", priority:1}
  ],
  cloze: {
    title:"第二册第5课 · Un resfriado",
    vocab:[
      ["el deportista","运动员"],["el aficionado","爱好者"],["el estadio","体育场"],["la piscina","游泳池"],
      ["la natación","游泳"],["el baloncesto","篮球"],["la chaqueta","夹克"],["el calor","热"],
      ["el viento","风"],["el cuerpo","身体"],["el dolor de cabeza","头疼"],["la nariz","鼻子"],
      ["el apetito","食欲"],["la frente","额头"],["la fiebre","发烧"],["el consultorio","诊室"],
      ["el pulso","脉搏"],["la lengua","舌头"],["la garganta","喉咙"],["el termómetro","体温计"],
      ["el resfriado","感冒"],["la tableta","药片"],["la inyección","注射"],["la enfermera","护士"]
    ],
    steps:[
      {label:"爱运动", text:"Marcos soñaba con ser un gran deportista, pero solo era un aficionado."},
      {label:"打篮球", text:"Jugaba un partido de baloncesto; el calor lo obligó a quitarse la chaqueta."},
      {label:"出汗吹风", text:"Sudaba mucho pero seguía corriendo. Empezó a soplar un viento fresco."},
      {label:"出现症状", text:"Tuvo un fuerte dolor de cabeza, la nariz tapada y ya no tenía apetito."},
      {label:"发烧就医", text:"Su madre le tocó la frente y le aconsejó ir al hospital."},
      {label:"医生检查", text:"Le tomó el pulso, le miró la lengua, le palpó la garganta y le puso el termómetro."},
      {label:"确诊开药", text:"Era un resfriado no muy grave. Le recetó tabletas y una inyección."},
      {label:"休息好转", text:"Durmió una tarde entera y ya se sentía mucho mejor."}
    ]
  },
  translations: [
    {zh:"那名男子进了咖啡馆，点了一杯咖啡，站着喝了，然后一声不吭地付了钱，走了。", es:"Aquel hombre entró en la cafetería, pidió un café, lo tomó de pie, luego pagó sin decir nada y se fue.", chunks:["entró en la cafetería","pidió un café","lo tomó de pie","pagó sin decir nada","se fue"]},
    {zh:"年轻人走近办公室，拿出钥匙，打开门，收拾了东西，放进包里，然后举起手来说声“后会有期”，就走了。", es:"El joven se acercó a la oficina, sacó la llave, abrió la puerta, recogió sus cosas, las metió en la bolsa, levantó la mano y dijo: «Hasta la vista», y se fue.", chunks:["se acercó a la oficina","sacó la llave","recogió sus cosas","las metió en la bolsa","levantó la mano"]},
    {zh:"周四下午四点到五点半我们听了一个关于西班牙文学的讲座。", es:"El jueves por la tarde, de cuatro a cinco y media, asistimos a una conferencia sobre literatura española.", chunks:["de cuatro a cinco y media","asistimos a una conferencia","sobre literatura española"]},
    {zh:"护士对我说：‘您别担心。如果您不能来医院，我会负责照看您母亲的。’", es:"La enfermera me dijo: «No se preocupe. Si no puede venir al hospital, yo me encargaré de cuidar a su madre». ", chunks:["No se preocupe","si no puede venir","me encargaré de cuidar"]},
    {zh:"公交车刚刚启动，前面不远处就发生了一场可怕的交通事故。眼看着交通开始堵塞，我们只得下车步行走完剩下的路程。", es:"El autobús acababa de arrancar cuando ocurrió un terrible accidente de tráfico no muy lejos. Al ver que el tráfico empezaba a atascarse, tuvimos que bajarnos y recorrer a pie el resto del camino.", chunks:["acababa de arrancar cuando","ocurrió un accidente","empezaba a atascarse","tuvimos que bajarnos","recorrer a pie"]},
    {zh:"你通知 Isabel，她不必去机场迎接代表团了。", es:"Avísale a Isabel que ya no es necesario que vaya al aeropuerto a recibir a la delegación.", chunks:["Avísale a Isabel","no es necesario que vaya","recibir a la delegación"]},
    {zh:"我没能打上出租车，只好步行去，结果晚到了许多。", es:"No pude conseguir un taxi, así que tuve que ir a pie; por eso llegué con mucho retraso.", chunks:["No pude conseguir","tuve que ir a pie","llegué con mucho retraso"]},
    {zh:"那女人对我们说她丈夫在警察局工作，总是很忙。", es:"La mujer nos dijo que su marido trabajaba en la comisaría y que siempre estaba muy ocupado.", chunks:["nos dijo que","trabajaba en la comisaría","estaba muy ocupado"]},
    {zh:"听他说话挺好玩的，他的发音怪怪的。", es:"Es bastante divertido escucharlo hablar; su pronunciación es un poco rara.", chunks:["Es bastante divertido","escucharlo hablar","su pronunciación es rara"]},
    {zh:"由于交通堵塞，我们赶到机场已经迟了，结果误了飞机。", es:"Debido al atasco, llegamos tarde al aeropuerto y perdimos el avión.", chunks:["Debido al atasco","llegamos tarde","perdimos el avión"]}
  ],
  passage16: [
    {es:"llevan cuatro años casados", zh:"已经结婚四年"},
    {es:"jóvenes, guapos, inteligentes y buenos profesionales", zh:"年轻、好看、聪明，而且都是优秀的专业人员"},
    {es:"forman un buen matrimonio", zh:"组成了一个美满的婚姻"},
    {es:"Él es médico y trabaja en un hospital público.", zh:"他是医生，在一家公立医院工作。"},
    {es:"Ella es farmacéutica y administra una farmacia.", zh:"她是药剂师，经营一家药店。"},
    {es:"la pareja trabaja en distintos centros", zh:"夫妻二人在不同的单位工作"},
    {es:"tiene horarios diferentes", zh:"作息时间不同"},
    {es:"raras veces regresan a la misma hora", zh:"他们很少在同一时间回家"},
    {es:"se encarga de la mayor parte de los quehaceres domésticos", zh:"负责大部分家务"},
    {es:"cambiarse de ropa", zh:"换衣服"},
    {es:"ponerse a barrer, a fregar, a lavar", zh:"开始扫地、擦洗、洗东西"},
    {es:"dejarlo todo en orden", zh:"把一切整理得井井有条"},
    {es:"toda la casa está bien arreglada y reluciente", zh:"整个家收拾得整洁明亮"},
    {es:"se olvida del cansancio", zh:"忘记疲劳"},
    {es:"sonríe con alegría y satisfacción", zh:"高兴而满足地微笑"},
    {es:"todo está a punto", zh:"一切准备就绪"},
    {es:"las verduras bien lavadas, la carne aliñada", zh:"蔬菜洗好了，肉调好了味"},
    {es:"los cacharros y utensilios necesarios", zh:"需要的锅碗瓢盆和用具"},
    {es:"encienda el fuego y se ponga a cocinar", zh:"点火并开始做饭"},
    {es:"Gracias, cariño.", zh:"谢谢你，亲爱的。"}
  ]
};
